name: All tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 17, 18 ] # test LTS versions, and the newest
        kotlin-version: [ 1.5.31, 1.6.21, 1.7.10 ]
        kotlin-ir-enabled: [ true, false ]
      fail-fast: false # in case one JDK fails, we still want to see results from others
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Run tests with Gradle
        run: >
          ./gradlew check
          --stacktrace
          -Pkotlin.version=${{ matrix.kotlin-version }}
          -Pkotlin.ir.enabled=${{ matrix.kotlin-ir-enabled }}
          -PjavaToolchainMainVersion=${{ matrix.java-version }}
          -PjavaToolchainTestVersion=${{ matrix.java-version }}

  android-instrumented-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 21, 29 ] # The minSdk and targetSdk versions set for MockK Android projects
      fail-fast: false # in case one API-level fails, we still want to see results from others
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: ${{ runner.os }}-avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedCheck
